DROP TABLE memory_save;
CREATE TABLE memory_save (
id NUMBER generated BY DEFAULT AS identity PRIMARY KEY,
uuid VARCHAR2(40) NOT NULL,
pairs NUMBER NOT NULL,
points NUMBER NOT NULL,
cards LONG NOT NULL
);